# Start from official Python base image
FROM python:3.13.2-slim-bullseye 

# create a virtual environment
RUN python -m venv /opt/venv

# Upgrade pip
RUN pip install --upgrade pip

#set python-related environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Adding the environment path variable 
ENV PATH="/opt/venv/bin:$PATH"

# Install system dependencies (only if needed, keep it minimal)
RUN apt-get update && apt-get install -y  \
    # for postgres
    libpq-dev \
    # for pillow
    libjpeg-dev \
    # for cairoSVG
    libcairo2 \
    #others
    gcc \
    && rm -rf /var/lib/apt/lists/*
    
#create a mini virtual machine code directory
RUN mkdir -p /code

# set the working directory to that same code directory 
WORKDIR /code

# Install the application dependencies first (leverage Docker cache)
COPY requirement.txt   /tmp/requirement.txt

#copy the source code into the container working directory 
COPY ./src /code/

# Install the python project requirements
RUN pip install -r /tmp/requirement.txt

# make the bash script executable
COPY ./boot/docker-run.sh /opt/run.sh
RUN chmod +x /opt/run.sh

# Clean up apt cache to reduce image size
RUN apt-get remove --purge -y \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Create and use non-root user for security
RUN useradd -m appuser
USER appuser

# Run the FastAPI project via the runtime script
# when the container starts
CMD ["/opt/run.sh"]
