# Start from official Python base image
FROM python:3.13.2-slim-bullseye 

# create a virtual environment
RUN python -m venv /opt/venv

# Upgrade pip
RUN pip install --upgrade pip

#set python-related environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Adding the environment path variable 
ENV PATH="/opt/venv/bin:$PATH"

# Install system dependencies (only if needed, keep it minimal)
RUN apt-get update && apt-get install -y  \
    # for postgres
    libpq-dev \
    # for pillow
    libjpeg-dev \
    # for cairoSVG
    libcairo2 \
    #others
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Install the application dependencies first (leverage Docker cache)
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r requirements.txt

# Copy in the source code
COPY src ./src

# Create and use non-root user for security
RUN useradd -m appuser
USER appuser

# Expose port (5000 in code, but CMD uses 8080 — let's align!)
EXPOSE 8080

# Run the application
CMD ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8080"]
