FROM python:3.13.2-slim-bullseye

# Create virtual environment
RUN python -m venv /opt/venv
RUN /opt/venv/bin/pip install --upgrade pip

#set the virtual environment as the current location
ENV PATH=/opt/venv/bin:$PATH

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1


# Install minimal system dependencies
RUN apt-get update && apt-get install -y \
    libpq-dev \
    libjpeg-dev \
    libcairo2 \
    gcc \
    && rm -rf /var/lib/apt/lists/*

# Create app directory
RUN mkdir -p /code
WORKDIR /code

# Copy and install Python dependencies
COPY requirement.txt /tmp/requirement.txt
RUN pip install -r /tmp/requirement.txt

# Copy source code
COPY ./src /code/

# Copy and set permissions for runtime script
COPY ./boot/docker-run.sh /opt/run.sh
RUN chmod 755 /opt/run.sh

# Create non-root user and set permissions
RUN useradd -m appuser \
    && chown -R appuser:appuser /code
USER appuser

# Start app
CMD ["/opt/run.sh"]
